name = "memos-worker"
compatibility_date = "2025-08-19"
main = "src/index.js"
[assets]
directory = "./src/public"
run_worker_first = [
	"/api/*"
]

[[d1_databases]]
binding = "DB"
database_id = "a7333d41-40aa-48dc-9266-610cc489cbb6"
database_name = "memos-worker-db"

[[kv_namespaces]]
binding = "NOTES_KV"
id = "9d9ac923a6e14fd7816bc1c9140e926c"
preview_id = ""

[[r2_buckets]]
binding = "NOTES_R2_BUCKET"
bucket_name = "memos-worker-r2"
preview_bucket_name = "notes-files-preview"
